server:
  port: 8080
  servlet:
    context-path: /samos-adapter

spring:
  application:
    name: samos-adapter-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_engine
    username: ${DB_USERNAME:payments_user}
    password: ${DB_PASSWORD:payments_password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Redis configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.payments.samosadapter: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"

# SAMOS Adapter specific configuration
samos:
  adapter:
    endpoint: ${SAMOS_ENDPOINT:https://samos.sarb.co.za/rtgs}
    api-version: v1
    timeout-seconds: 30
    retry-attempts: 3
    encryption-enabled: true
    certificate-path: ${SAMOS_CERT_PATH:/etc/certs/samos.p12}
    certificate-password: ${SAMOS_CERT_PASSWORD:}
    
  # ISO 20022 message configuration
  iso20022:
    namespace: urn:iso:std:iso:20022:tech:xsd
    version: 2013-05-01
    message-types:
      - pacs.008  # FIToFICstmrCdtTrf (Credit Transfer)
      - pacs.002 # FIToFIPmtStsRpt (Payment Status Report)
      - camt.054 # BkToCstmrDbtCdtNtfctn (Bank to Customer Debit/Credit Notification)

# Resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      samos-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      samos-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
  timelimiter:
    instances:
      samos-service:
        timeout-duration: 30s
        cancel-running-future: true

# Feign client configuration
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 30000
        logger-level: basic
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
    connection-timeout: 5000
    time-to-live: 900
