spring:
  application:
    name: routing-service
  
  profiles:
    active: dev
    
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/payments_routing}
    username: ${DATABASE_USERNAME:routing_user}
    password: ${DATABASE_PASSWORD:routing_password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        order_inserts: true
        order_updates: true
        batch_size: 20
        fetch_size: 20
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    
  data:
    redis:
      host: ${redis.host:localhost}
      port: ${redis.port:6379}
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Routing Service Configuration
routing:
  service:
    cache:
      ttl: 300000  # 5 minutes
      max-size: 1000
    rules:
      max-conditions: 10
      max-actions: 5
      evaluation-timeout: 5000  # 5 seconds
    clearing-systems:
      primary: PRIMARY_CLEARING
      secondary: SECONDARY_CLEARING
      local: LOCAL_CLEARING
      international: INTERNATIONAL_CLEARING

# OpenTelemetry Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,opentelemetry
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

# Logging Configuration
logging:
  level:
    com.payments.routing: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"

# Server Configuration
server:
  port: 8084
  servlet:
    context-path: /routing-service
