server:
  port: 8085

spring:
  application:
    name: swift-adapter-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_engine
    username: ${DB_USERNAME:payments_user}
    password: ${DB_PASSWORD:payments_password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# SWIFT Adapter Configuration
swift:
  adapter:
    endpoint: ${SWIFT_ENDPOINT:https://swift.com/api}
    timeout: ${SWIFT_TIMEOUT:10000}
    retry-attempts: ${SWIFT_RETRY_ATTEMPTS:3}
    network: ${SWIFT_NETWORK:SWIFT}
    currency: ${SWIFT_CURRENCY:USD}
    sanctions:
      screening:
        enabled: ${SANCTIONS_SCREENING_ENABLED:true}
        endpoint: ${SANCTIONS_ENDPOINT:https://sanctions.screening.com/api}
        timeout: ${SANCTIONS_TIMEOUT:5000}
        retry-attempts: ${SANCTIONS_RETRY_ATTEMPTS:2}
    fx:
      conversion:
        enabled: ${FX_CONVERSION_ENABLED:true}
        endpoint: ${FX_ENDPOINT:https://fx.conversion.com/api}
        timeout: ${FX_TIMEOUT:3000}
        retry-attempts: ${FX_RETRY_ATTEMPTS:2}

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      swift-adapter:
        failure-rate-threshold: 40
        wait-duration-in-open-state: 60s
        sliding-window-size: 20
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 5
      sanctions-screening:
        failure-rate-threshold: 30
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
      fx-conversion:
        failure-rate-threshold: 35
        wait-duration-in-open-state: 45s
        sliding-window-size: 15
        minimum-number-of-calls: 8
        permitted-number-of-calls-in-half-open-state: 4
  retry:
    instances:
      swift-adapter:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
      sanctions-screening:
        max-attempts: 2
        wait-duration: 1s
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
      fx-conversion:
        max-attempts: 2
        wait-duration: 1s
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
  timelimiter:
    instances:
      swift-adapter:
        timeout-duration: 10s
      sanctions-screening:
        timeout-duration: 5s
      fx-conversion:
        timeout-duration: 3s

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.payments.swiftadapter: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
