# Minimal Payment Processing Service Configuration
# This configuration disables complex features to focus on ISO 20022 processing

server:
  port: 8082
  servlet:
    context-path: /payment-processing

spring:
  application:
    name: payment-processing-service
  
  profiles:
    active: minimal
  
  # Disable database features for now
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  
  # Disable Flyway
  flyway:
    enabled: false
  
  # Disable Redis for now
  data:
    redis:
      repositories:
        enabled: false
  
  # Disable Kafka for now
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-processing-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

# Disable Eureka for now
eureka:
  client:
    enabled: false

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.paymentengine.paymentprocessing: INFO
    org.springframework: WARN
    org.hibernate: WARN