# Kibana configuration for Payment Engine

server.name: payment-engine-kibana
server.host: "0.0.0.0"
server.port: 5601

# Elasticsearch connection
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.requestTimeout: 30000
elasticsearch.pingTimeout: 3000

# Security (disabled for development)
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "payment-engine-kibana-encryption-key-32-chars"

# Monitoring
monitoring.ui.container.elasticsearch.enabled: true
monitoring.kibana.collection.enabled: false

# Logging
logging.appenders.file.type: file
logging.appenders.file.fileName: /usr/share/kibana/logs/kibana.log
logging.appenders.file.layout.type: json

logging.root.level: info
logging.loggers:
  - name: elasticsearch.query
    level: warn
  - name: http.server.response
    level: warn

# Index patterns for Payment Engine
kibana.defaultAppId: "dashboard"

# Custom branding
server.customResponseHeaders:
  "X-Frame-Options": "DENY"
  "X-Content-Type-Options": "nosniff"
  "X-XSS-Protection": "1; mode=block"

# Advanced settings
elasticsearch.shardTimeout: 30000
elasticsearch.requestHeadersWhitelist: ["authorization", "x-forwarded-for", "x-forwarded-proto", "x-proxy-user", "x-proxy-roles", "x-forwarded-server", "x-forwarded-host"]

# Telemetry
telemetry.enabled: false
telemetry.optIn: false

# Maps (if needed for geographical analysis)
map.includeElasticMapsService: false

# Dashboard and visualization settings
visualization.colorMapping: {}
dashboard.defaultDarkMode: false