server:
  port: 8080
  servlet:
    context-path: /api/v1/auth

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_engine_auth
    username: ${DB_USERNAME:payment_engine}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  security:
    oauth2:
      authorization-server:
        issuer: https://auth.payment-engine.local
        client:
          registration:
            payment-engine-client:
              client-id: payment-engine-client
              client-secret: ${OAUTH_CLIENT_SECRET:secret}
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://localhost:3000/callback
              scopes:
                - read
                - write
                - openid
                - profile
                - email

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidation}
    expiration: 3600
    refresh-expiration: 86400
    issuer: payment-engine-auth

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.paymentengine.auth: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      auth-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      auth-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.lang.Exception
  timelimiter:
    instances:
      auth-service:
        timeout-duration: 30s
        cancel-running-future: true
  bulkhead:
    instances:
      auth-service:
        max-concurrent-calls: 10
        max-wait-duration: 1s