# Logstash configuration for Payment Engine

http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# Pipeline configuration
path.config: /usr/share/logstash/pipeline
config.reload.automatic: true
config.reload.interval: 3s

# Logging
log.level: info
path.logs: /usr/share/logstash/logs

# JVM settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Monitoring
xpack.monitoring.enabled: true