spring:
  application:
    name: audit-service

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_engine
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        use_sql_comments: true
    show-sql: false

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration

  # Kafka Configuration (Event Consumer)
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: audit-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 100
    properties:
      isolation:
        level: read_committed

  # Caching Configuration (Redis)
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1 hour in milliseconds

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:https://payments.b2clogin.com/payments.onmicrosoft.com/v2.0/}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:https://payments.b2clogin.com/payments.onmicrosoft.com/discovery/v2.0/keys}
          audiences: ${OAUTH2_AUDIENCE:04c4c63e-c77e-4be9-aab3-1b7b53d45e21}

# Server Configuration
server:
  port: 8083
  servlet:
    context-path: /
  compression:
    enabled: true
    min-response-size: 1024

# Logging Configuration
logging:
  level:
    root: INFO
    com.payments.audit: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator / Observability Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

# Application Custom Properties
app:
  name: Audit Service
  version: 1.0.0
  audit:
    enabled: true
    retention-days: 2555  # 7 years
    batch-size: 100
    flush-interval-seconds: 60
  multi-tenancy:
    enabled: true
  kafka:
    audit-topic: payment-audit-logs
    consumer-concurrency: 3
