apiVersion: v1
kind: Namespace
metadata:
  name: payment-engine
  labels:
    name: payment-engine
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system