# Traffic routing and canary deployment configuration
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: payment-service-routing
  namespace: payments
spec:
  hosts:
    - payment-service
  http:
    # Default routing - can be modified for canary deployments
    - route:
        - destination:
            host: payment-service
            subset: v1
          weight: 100

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: account-service-routing
  namespace: payments
spec:
  hosts:
    - account-service
  http:
    - route:
        - destination:
            host: account-service
            subset: v1
          weight: 100

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: validation-service-routing
  namespace: payments
spec:
  hosts:
    - validation-service
  http:
    - route:
        - destination:
            host: validation-service
            subset: v1
          weight: 100

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: saga-orchestrator-routing
  namespace: payments
spec:
  hosts:
    - saga-orchestrator
  http:
    - route:
        - destination:
            host: saga-orchestrator
            subset: v1
          weight: 100

---
# Canary deployment example for payment service
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: payment-service-canary
  namespace: payments
spec:
  hosts:
    - payment-service
  http:
    # Route 90% to v1, 10% to v2 (canary)
    - route:
        - destination:
            host: payment-service
            subset: v1
          weight: 90
        - destination:
            host: payment-service
            subset: v2
          weight: 10
