# Filebeat configuration for Payment Engine

filebeat.inputs:
  # Docker container logs
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
    fields:
      logSource: "docker"
      environment: "${ENVIRONMENT:development}"
    fields_under_root: true
    
    # Only collect logs from Payment Engine containers
    include_lines: ['payment-engine', 'core-banking', 'payment-processing', 'api-gateway']
    
  # Application log files (if mounted)
  - type: log
    enabled: true
    paths:
      - /app/logs/*.log
      - /var/log/payment-engine/*.log
    fields:
      logSource: "application"
      environment: "${ENVIRONMENT:development}"
    fields_under_root: true
    multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    multiline.negate: true
    multiline.match: after

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - timestamp:
      field: timestamp
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05.000000Z'
      test:
        - '2023-01-02T15:04:05.000Z'

# Output configuration
output.logstash:
  hosts: ["logstash:5044"]
  worker: 2
  compression_level: 3
  bulk_max_size: 1024
  template.name: "payment-engine-logs"
  template.pattern: "payment-engine-logs-*"

# Alternative: Direct to Elasticsearch
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   index: "payment-engine-logs-%{+yyyy.MM.dd}"
#   template.name: "payment-engine-logs"
#   template.pattern: "payment-engine-logs-*"

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]

# Security
ssl.verification_mode: none