server:
  port: 8083
  servlet:
    context-path: /api/v1/rtc

spring:
  application:
    name: rtc-adapter-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_engine
    username: ${DB_USERNAME:payments_user}
    password: ${DB_PASSWORD:payments_pass}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# RTC Adapter Configuration
rtc:
  adapter:
    endpoint: ${RTC_ENDPOINT:https://rtc.bankservafrica.co.za/api/v1}
    timeout: ${RTC_TIMEOUT:10000}
    retry-attempts: ${RTC_RETRY_ATTEMPTS:3}
    amount-limit: ${RTC_AMOUNT_LIMIT:5000.00}
    currency: ${RTC_CURRENCY:ZAR}
    availability: 24/7/365
    
  iso20022:
    namespace: urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08
    version: 8.1.8
    message-type: pacs.008
    
  resilience:
    circuit-breaker:
      failure-rate-threshold: 50
      wait-duration-in-open-state: 30s
      sliding-window-size: 10
    retry:
      max-attempts: 3
      wait-duration: 1s
    time-limiter:
      timeout-duration: 10s

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.payments.rtcadapter: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
