apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: payment-engine-akv
spec:
  provider:
    azurekv:
      vaultUrl: https://payment-engine-kv.vault.azure.net/
      tenantId: 00000000-0000-0000-0000-000000000000
      authSecretRef:
        clientId:
          name: akv-service-principal
          key: clientId
          namespace: external-secrets
        clientSecret:
          name: akv-service-principal
          key: clientSecret
          namespace: external-secrets
        tenantId:
          name: akv-service-principal
          key: tenantId
          namespace: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: akv-service-principal
  namespace: external-secrets
type: Opaque
stringData:
  clientId: "set-by-pipeline"
  clientSecret: "set-by-pipeline"
  tenantId: "set-by-pipeline"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-engine-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: payment-engine-akv
    kind: ClusterSecretStore
  target:
    name: payment-engine-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: database-password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: jwt-signing-secret
    - secretKey: AZURE_CLIENT_ID
      remoteRef:
        key: aad-client-id
    - secretKey: AZURE_CLIENT_SECRET
      remoteRef:
        key: aad-client-secret
    - secretKey: AZURE_TENANT_ID
      remoteRef:
        key: aad-tenant-id
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: platform-encryption-key
    - secretKey: NOTIFICATION_SERVICE_API_KEY
      remoteRef:
        key: notification-service-api-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: payment-engine-akv
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: grafana-admin-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: payment-engine-akv
    kind: ClusterSecretStore
  target:
    name: postgresql-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-password
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres-username
    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgres-database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-engine-tls
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: payment-engine-akv
    kind: ClusterSecretStore
  target:
    name: payment-engine-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: tls-certificate
    - secretKey: tls.key
      remoteRef:
        key: tls-private-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-secret
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: payment-engine-akv
    kind: ClusterSecretStore
  target:
    name: registry-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: acr-dockerconfigjson
