apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-config
  namespace: payment-engine
data:
  # Multi-tenant configuration
  tenancy.enabled: "true"
  tenancy.default-tenant: "default"
  tenancy.isolation-level: "ROW_LEVEL_SECURITY"
  
  # Configuration service settings
  config.cache.enabled: "true"
  config.cache.ttl: "3600"
  config.validation.enabled: "true"
  
  # Feature flag settings
  feature-flags.enabled: "true"
  feature-flags.cache.enabled: "true"
  feature-flags.rollout.enabled: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: tenant-secrets
  namespace: payment-engine
type: Opaque
stringData:
  # Configuration encryption key
  config.encryption.key: "your-config-encryption-key-here"
  
  # Tenant database credentials
  tenant.db.username: "tenant_admin"
  tenant.db.password: "tenant_admin_password"

---
# ConfigMap for tenant-specific environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-environment
  namespace: payment-engine
data:
  # JVM settings for multi-tenancy
  JAVA_OPTS: "-Xms512m -Xmx2048m -XX:+UseG1GC -Dspring.profiles.active=production,multi-tenant"
  
  # Database settings
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/payment_engine"
  SPRING_DATASOURCE_USERNAME: "payment_user"
  
  # Redis settings for tenant caching
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_DATABASE: "1"
  
  # Kafka settings
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "payment-engine-multi-tenant"
  
  # Tenant-specific Kafka topics
  KAFKA_TENANT_TOPICS_ENABLED: "true"
  KAFKA_TENANT_TOPIC_PREFIX: "tenant"
  
  # Configuration service settings
  CONFIG_SERVICE_ENABLED: "true"
  CONFIG_SERVICE_CACHE_ENABLED: "true"
  CONFIG_SERVICE_VALIDATION_ENABLED: "true"
  
  # Feature flags
  FEATURE_FLAGS_ENABLED: "true"
  FEATURE_FLAGS_CACHE_TTL: "300"
  
  # Monitoring
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,metrics,prometheus,configprops,env"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_METRICS_TAGS_APPLICATION: "payment-engine"
  MANAGEMENT_METRICS_TAGS_ENVIRONMENT: "production"

---
# RBAC for tenant management
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-manager
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-manager
subjects:
- kind: ServiceAccount
  name: payment-engine-service-account
  namespace: payment-engine

---
# Service Account for tenant operations
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-engine-service-account
  namespace: payment-engine
automountServiceAccountToken: true