spring:
  application:
    name: transaction-processing-service-test
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false
    
  flyway:
    enabled: false
    
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      
  cache:
    type: simple
      
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 0
    consumer:
      group-id: transaction-processing-service-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.payments.transactionprocessing: DEBUG
    org.springframework.cache: DEBUG
    org.testcontainers: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Transaction Processing Service Test Configuration
transaction-processing:
  ledger:
    balance-cache-ttl: 60 # 1 minute for tests
    enable-double-entry-validation: true
  events:
    enable-event-sourcing: true
    event-retention-days: 1
  clearing:
    supported-systems:
      - CHAPS
      - BACS
      - FPS






