package com.payments.domain.valueobjects;

public enum NotificationType {
    PAYMENT_INITIATED,
    PAYMENT_VALIDATED,
    PAYMENT_SUBMITTED_TO_CLEARING,
    PAYMENT_CLEARED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PAYMENT_REVERSED,
    TRANSACTION,
    TRANSACTION_CREATED,
    TRANSACTION_PROCESSING,
    TRANSACTION_CLEARING,
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    TENANT_CREATED,
    TENANT_ACTIVATED,
    TENANT_SUSPENDED,
    USER_ADDED,
    BUSINESS_UNIT_ADDED,
    CONFIGURATION_UPDATED,
    SYSTEM_ALERT,
    MAINTENANCE_NOTICE,
    SECURITY_ALERT
}
