# Telemetry Configuration
telemetry:
  tracing:
    enabled: true
    exporter: jaeger
    service:
      name: payments-engine
      version: 0.1.0
    jaeger:
      endpoint: http://localhost:14250
    otlp:
      endpoint: http://localhost:4317
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans
      
  metrics:
    enabled: true
    prometheus:
      enabled: true
    service:
      name: payments-engine
      
  logging:
    enabled: true
    structured: true
    level: INFO
    file:
      path: logs/payments-engine.log
      max-size: 100MB
      max-history: 30

# OpenTelemetry Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.payments: INFO
    io.opentelemetry: WARN
    io.micrometer: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] [%X{tenantId}] [%X{paymentId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] [%X{tenantId}] [%X{paymentId}] %logger{36} - %msg%n"






