groups:
  - name: tenant-specific-alerts
    rules:
      # Tenant-specific transaction volume alerts
      - alert: TenantHighTransactionVolume
        expr: sum(rate(payment_transactions_total{tenant_id!=""}[5m])) by (tenant_id) > 1000
        for: 2m
        labels:
          severity: warning
          component: transactions
        annotations:
          summary: "High transaction volume for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} is processing {{ $value }} transactions per second, which is above the threshold of 1000."
          tenant_id: "{{ $labels.tenant_id }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/tenant-high-volume"

      # Tenant-specific error rate alerts
      - alert: TenantHighErrorRate
        expr: (sum(rate(payment_transactions_total{tenant_id!="",status="ERROR"}[5m])) by (tenant_id) / sum(rate(payment_transactions_total{tenant_id!=""}[5m])) by (tenant_id)) * 100 > 5
        for: 5m
        labels:
          severity: critical
          component: transactions
        annotations:
          summary: "High error rate for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} has an error rate of {{ $value }}%, which is above the 5% threshold."
          tenant_id: "{{ $labels.tenant_id }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/tenant-high-errors"

      # Tenant-specific API rate limit alerts
      - alert: TenantRateLimitExceeded
        expr: sum(rate(api_requests_rate_limited_total{tenant_id!=""}[5m])) by (tenant_id) > 0
        for: 1m
        labels:
          severity: warning
          component: api-gateway
        annotations:
          summary: "Rate limit exceeded for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} is being rate limited with {{ $value }} requests per second being rejected."
          tenant_id: "{{ $labels.tenant_id }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/tenant-rate-limit"

      # Tenant resource usage alerts
      - alert: TenantResourceUsageHigh
        expr: tenant_resource_usage_percentage{tenant_id!=""} > 80
        for: 5m
        labels:
          severity: warning
          component: resources
        annotations:
          summary: "High resource usage for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} is using {{ $value }}% of their allocated {{ $labels.resource_type }} resources."
          tenant_id: "{{ $labels.tenant_id }}"
          resource_type: "{{ $labels.resource_type }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/tenant-resource-usage"

      # Tenant configuration change alerts
      - alert: TenantConfigurationChanged
        expr: increase(tenant_configuration_changes_total{tenant_id!=""}[1h]) > 10
        for: 0m
        labels:
          severity: info
          component: configuration
        annotations:
          summary: "Frequent configuration changes for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} has had {{ $value }} configuration changes in the last hour."
          tenant_id: "{{ $labels.tenant_id }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/tenant-config-changes"

      # Tenant feature flag rollout alerts
      - alert: TenantFeatureFlagRollout
        expr: tenant_feature_flag_rollout_percentage{tenant_id!=""} > 0 and tenant_feature_flag_rollout_percentage{tenant_id!=""} < 100
        for: 0m
        labels:
          severity: info
          component: feature-flags
        annotations:
          summary: "Feature flag rollout in progress for tenant {{ $labels.tenant_id }}"
          description: "Feature {{ $labels.feature_name }} is being rolled out to {{ $value }}% of users for tenant {{ $labels.tenant_id }}."
          tenant_id: "{{ $labels.tenant_id }}"
          feature_name: "{{ $labels.feature_name }}"

      # Tenant ISO 20022 message processing alerts
      - alert: TenantIso20022ProcessingErrors
        expr: sum(rate(iso20022_message_processing_errors_total{tenant_id!=""}[5m])) by (tenant_id, message_type) > 0.1
        for: 5m
        labels:
          severity: warning
          component: iso20022
        annotations:
          summary: "ISO 20022 processing errors for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} is experiencing {{ $value }} errors per second processing {{ $labels.message_type }} messages."
          tenant_id: "{{ $labels.tenant_id }}"
          message_type: "{{ $labels.message_type }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/iso20022-errors"

      # Tenant database connection alerts
      - alert: TenantDatabaseConnectionsHigh
        expr: sum(database_connections_active{tenant_id!=""}) by (tenant_id) > 80
        for: 3m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "High database connections for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} is using {{ $value }} database connections, which is approaching the limit."
          tenant_id: "{{ $labels.tenant_id }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/tenant-db-connections"

      # Tenant Kafka lag alerts
      - alert: TenantKafkaConsumerLag
        expr: kafka_consumer_lag_sum{tenant_id!=""} > 1000
        for: 5m
        labels:
          severity: warning
          component: messaging
        annotations:
          summary: "High Kafka consumer lag for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} has a consumer lag of {{ $value }} messages on topic {{ $labels.topic }}."
          tenant_id: "{{ $labels.tenant_id }}"
          topic: "{{ $labels.topic }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/tenant-kafka-lag"

      # Tenant SLA breach alerts
      - alert: TenantSLABreach
        expr: tenant_sla_compliance_percentage{tenant_id!=""} < 99.9
        for: 1m
        labels:
          severity: critical
          component: sla
        annotations:
          summary: "SLA breach for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} SLA compliance is {{ $value }}% for {{ $labels.sla_type }}, below the 99.9% target."
          tenant_id: "{{ $labels.tenant_id }}"
          sla_type: "{{ $labels.sla_type }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/tenant-sla-breach"

  - name: tenant-capacity-planning
    rules:
      # Tenant growth rate tracking
      - record: tenant_transaction_growth_rate
        expr: rate(payment_transactions_total{tenant_id!=""}[1d])

      - record: tenant_api_usage_growth_rate
        expr: rate(api_requests_total{tenant_id!=""}[1d])

      # Tenant resource efficiency
      - record: tenant_resource_efficiency
        expr: tenant_transaction_volume / tenant_resource_usage

      # Tenant cost per transaction
      - record: tenant_cost_per_transaction
        expr: tenant_infrastructure_cost / tenant_transaction_volume

  - name: tenant-security-alerts
    rules:
      # Tenant authentication failures
      - alert: TenantAuthenticationFailures
        expr: sum(rate(authentication_failures_total{tenant_id!=""}[5m])) by (tenant_id) > 10
        for: 2m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "High authentication failures for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} has {{ $value }} authentication failures per second."
          tenant_id: "{{ $labels.tenant_id }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/tenant-auth-failures"

      # Tenant suspicious activity
      - alert: TenantSuspiciousActivity
        expr: tenant_fraud_score{tenant_id!=""} > 0.8
        for: 1m
        labels:
          severity: critical
          component: security
        annotations:
          summary: "Suspicious activity detected for tenant {{ $labels.tenant_id }}"
          description: "Tenant {{ $labels.tenant_id }} has a fraud score of {{ $value }}, indicating potential suspicious activity."
          tenant_id: "{{ $labels.tenant_id }}"
          runbook_url: "https://docs.paymentengine.com/runbooks/tenant-fraud-detection"