# Minimal Payment Processing Service Configuration
server:
  port: 8082
  servlet:
    context-path: /payment-processing

spring:
  application:
    name: payment-processing-minimal-service

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.paymentengine.paymentprocessing: INFO
    org.springframework: WARN
    org.hibernate: WARN