spring:
  application:
    name: payment-initiation-service-test
  
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-initiation-test
      auto-offset-reset: earliest
    producer:
      acks: all
      retries: 3
      
  security:
    oauth2:
      client:
        registration:
          account-service:
            client-id: test-client
            client-secret: test-secret
            authorization-grant-type: client_credentials
            scope: payments:read,payments:write
        provider:
          account-service:
            token-uri: http://localhost:8080/oauth/token
            
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    com.payments: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
server:
  port: 0  # Random port for tests
  
testcontainers:
  enabled: true
