# Production environment overrides
components:
  apiGateway:
    replicaCount: 4
    autoscaling:
      minReplicas: 4
      maxReplicas: 12
    ingress:
      hosts:
        - host: api.payment-engine.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: payment-engine-tls
          hosts:
            - api.payment-engine.example.com
  paymentProcessing:
    replicaCount: 5
    autoscaling:
      minReplicas: 5
      maxReplicas: 15
  authService:
    replicaCount: 3
    autoscaling:
      minReplicas: 3
      maxReplicas: 9
