# Staging environment overrides
components:
  apiGateway:
    replicaCount: 2
    autoscaling:
      minReplicas: 2
      maxReplicas: 6
    ingress:
      hosts:
        - host: staging-api.payment-engine.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: payment-engine-tls
          hosts:
            - staging-api.payment-engine.example.com
  paymentProcessing:
    replicaCount: 2
    autoscaling:
      minReplicas: 2
      maxReplicas: 6
  authService:
    replicaCount: 2
    autoscaling:
      minReplicas: 2
      maxReplicas: 6
