spring:
  datasource:
    url: jdbc:tc:postgresql:15:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers:${KAFKA_BOOTSTRAP_SERVERS:}}
    consumer:
      group-id: audit-service-group-e2e
      auto-offset-reset: earliest

logging:
  level:
    root: INFO

app:
  audit:
    flush-interval-seconds: 1
