server:
  port: 8080
  servlet:
    context-path: /payment-initiation

spring:
  application:
    name: payment-initiation-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_engine
    username: ${DB_USERNAME:payments_user}
    password: ${DB_PASSWORD:payments_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "format_sql": true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  kafka:
    audit-topic: payment-audit-logs

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# Logging
logging:
  level:
    "com.payments.paymentinitiation": DEBUG
    "org.springframework.web": INFO
    "org.hibernate.SQL": DEBUG
    "org.hibernate.type.descriptor.sql.BasicBinder": TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"

# Application specific (reserve for future use via @ConfigurationProperties if needed)
