spring:
  application:
    name: tenant-management-service
  profiles:
    active: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_engine
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes
      cache-null-values: false

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
      timeout: 5000ms

  jmx:
    enabled: true

server:
  port: 8081
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
    min-response-size: 1024

logging:
  level:
    root: INFO
    com.payments: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/tenant-management-service.log
    max-size: 10MB
    max-history: 10

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      include: db,diskSpace,ping
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 100ms,250ms,500ms,1000ms
  tracing:
    sampling:
      probability: 1.0

security:
  jwt:
    secret: ${JWT_SECRET:your-secret-key-change-in-production}
    expiration: 3600000 # 1 hour
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Content-Type,Authorization,X-Tenant-ID,X-Correlation-ID
    max-age: 3600

tenant:
  isolation:
    enabled: true
    use-rls: true # Row-Level Security
  
  cache:
    ttl-minutes: 10
    max-entries: 10000

azure:
  keyvault:
    enabled: ${AZURE_KEYVAULT_ENABLED:false}
    vault-uri: ${AZURE_KEYVAULT_URI:}
  
  servicebus:
    connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING:}
    queue-name: tenant.events

---

# Development Profile
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.payments: DEBUG
    org.springframework.web: DEBUG

---

# Production Profile
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      maximum-pool-size: 50

logging:
  level:
    root: WARN
    com.payments: INFO

security:
  jwt:
    secret: ${JWT_SECRET}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
