{{- $root := . -}}
{{- range $name, $component := .Values.components }}
{{- if and $component.enabled $component.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "payment-engine.component-name" (list $root $component $name) }}
  labels:
    {{- include "payment-engine.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name | replace "_" "-" | lower }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "payment-engine.component-name" (list $root $component $name) }}
  minReplicas: {{ $component.autoscaling.minReplicas }}
  maxReplicas: {{ $component.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $component.autoscaling.targetCPUUtilizationPercentage }}
{{- if $component.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $component.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
---
{{- end }}
{{- end }}
